Models/salary_Result.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    
    public partial class salary_Result
    {
        public int Doctor_idDoctor { get; set; }
        public string fullname { get; set; }
        public Nullable<decimal> Зарплата { get; set; }
        public Nullable<decimal> налог { get; set; }
    }
}

Controllers/vedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class vedController : Controller
    {
        // GET: ved
        public ActionResult Index()
        {
            return View();
        }
        private HospitalEntities db = new HospitalEntities();
        public ActionResult salary_Result(DateTime firsDate, DateTime lastDate)
        {
            var query = "exec salary '" + firsDate.ToString("yyyyMMdd HH:mm: ss") + "', '" + lastDate.ToString("yyyyMMdd HH: mm:ss") + "'";
            Console.WriteLine(query);
            var qq = db.Database.SqlQuery<salary_Result>(query);
            return View(qq.ToList());
        }
    }
}

Views/ved/Index.cshtml
@model WebApplication4.Models.salary_Result

@{
    ViewBag.Title = "View";
}

<h2>Ведомости</h2>

@using (Html.BeginForm("salary_Result", "ved"))
{
    @Html.AntiForgeryToken()


    <div class="form-group">
        <label for="firsDate" class="control-label col-md-2">Начальная дата</label>
        <input type="date" name="firsDate" id="firsDate" class="form-control">
    </div>
    <div class="form-group">
        <label for="lastDate" class="control-label col-md-2">Конечная дата</label>
        <input type="date" name="lastDate" id="lastDate" class="form-control">
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Выполнить" class="btn btn-default" />
        </div>
    </div>
}

Views/ved/salary_Result.cshtml
@model IEnumerable<WebApplication4.Models.salary_Result>

@{
    ViewBag.Title = "salaryResult";
}

<h2>salaryResult</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Doctor_idDoctor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fullname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Зарплата)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.налог)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Doctor_idDoctor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fullname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Зарплата)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.налог)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>