Models/kvitancia_Result.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    
    public partial class kvitancia_Result
    {
        public string fullname { get; set; }
        public Nullable<System.DateTime> datee { get; set; }
        public Nullable<int> price { get; set; }
    }
}

Controllers/kvitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;


namespace WebApplication4.Controllers
{
    public class kvitController : Controller
    {
        // GET: kvit
        public ActionResult Index()
        {
            return View();
        }
        private HospitalEntities db = new HospitalEntities();
        public ActionResult kvitancia_Result(int idP)
        {
            var query = "exec kvitancia " + idP;
            Console.WriteLine(query);
            var qq = db.Database.SqlQuery<kvitancia_Result>(query);
            return View(qq.ToList());
        }
    }
    
    

}

Views/kvit/Index.cshtml
@model WebApplication4.Models.kvitancia_Result

@{
    ViewBag.Title = "Квитанции";
}

<h2>Квитанции</h2>

@using (Html.BeginForm("kvitancia_Result", "kvit"))
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">
        <h4>Введите id Пациента</h4>
        <div class="form-group">
            <div class="col-md-10">
                @Html.TextBox("idP")
            </div>
        </div>
        <div>
            <input type="submit" value="Получить квитанцию" class="btnbtn-primary" />
        </div>
    </div>
}

Views/kvit/kvitancia_Result.cshtml
@model IEnumerable<WebApplication4.Models.kvitancia_Result>

@{
    ViewBag.Title = "kvitancia_Result";
}

<h2>kvitancia_Result</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.fullname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.datee)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.fullname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.datee)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.price)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>